// Glitchlands bug bank: every program is hand-written and machine-checked (see tests/bank.test.js).
// § marks the buggy line; "out" is exactly what the fixed program prints (including hidden "extra" test lines).
const RAW=[
{title:"Coin Collector Glitch",out:["Total: 40"],task:"Add up all the coins the player picked up.",category:"wrong-operator",expected:"Total: 40",actual:"Total: 25",
 code:`const coins = [5, 10, 25];\nlet total = 0;\n\nfor (let i = 0; i < coins.length; i++) {\n§  total = coins[i];\n}\n\nconsole.log("Total:", total);`,
 hints:["Does the answer look like the sum, or like one of the inputs?","What happens to the old total on each pass of the loop?","Which operator keeps the old value AND adds a new one?"],
 fix:"total += coins[i];",explanation:"= replaces the value, += accumulates. In a running total, ask: is the old value kept?"},
{title:"Countdown Lift-Off",out:["Countdown!", "3", "2", "1", "Liftoff!"],task:"Print 3, 2, 1 and then 'Liftoff!'.",category:"infinite-loop",expected:"3 2 1 Liftoff!",actual:"3, 4, 5, 6... it never stops (the page hangs)",
 code:`console.log("Countdown!");\n\n§for (let i = 3; i > 0; i++) {\n  console.log(i);\n}\n\nconsole.log("Liftoff!");`,
 hints:["The rocket never launches. Which line decides when the loop stops?","The loop stops when its condition turns false. Does i move toward that?","Starting at 3 and wanting to reach 0: should i go up or down?"],
 fix:"for (let i = 3; i > 0; i--) {",explanation:"A loop only ends if each pass moves the variable toward making the condition false. Check the direction of the step."},
{title:"The Lonely Last Song",out:["1 Intro", "2 Sunrise", "3 Neon", "4 Outro", "Total: 4"],task:"Print every song in the playlist.",category:"off-by-one",expected:"4 songs printed",actual:"Only 3 printed. 'Outro' is missing",
 code:`const playlist = ["Intro", "Sunrise", "Neon", "Outro"];\n\n§for (let i = 0; i < playlist.length - 1; i++) {\n  console.log(i + 1, playlist[i]);\n}\n\nconsole.log("Total:", playlist.length);`,
 hints:["Count the lines printed against the total. What's different?","The last item is missing. Something at the loop's edge is cut short.","With 4 items, what is the last valid index, and does this loop reach it?"],
 fix:"for (let i = 0; i < playlist.length; i++) {",explanation:"Indexes run 0 to length-1, so i < length already covers every item. Subtracting 1 drops the last one."},
{title:"The Silent Function",out:["Area is 20", "6 100"],extra:"console.log(area(2, 3), area(10, 10));",task:"Return the area of a rectangle.",category:"missing-return",expected:"Area is 20",actual:"Area is undefined",
 code:`function area(w, h) {\n§  const result = w * h;\n}\n\nconst a = area(4, 5);\nconsole.log("Area is", a);`,
 hints:["The value printed isn't a number at all. What is it?","The function computes something. Where does that value go afterwards?","How does a function hand its answer back to the code that called it?"],
 fix:"return w * h;",explanation:"Computing a value is not the same as returning it. Without return, a JavaScript function gives back undefined."},
{title:"Is It Legal to Drive?",out:["true", "true", "false true true"],extra:"console.log(canDrive(17), canDrive(18), canDrive(30));",task:"Return true when the age is 18 or older.",category:"bad-condition",expected:"true, true",actual:"false, true",
 code:`function canDrive(age) {\n§  if (age > 18) {\n    return true;\n  }\n  return false;\n}\n\nconsole.log(canDrive(18)); // should be true\nconsole.log(canDrive(25));`,
 hints:["Only one of the two test calls is wrong. Which input is special?","It's the boundary value that fails. What is 18 compared against 18?","'older than 18' and '18 or older'. Are those the same?"],
 fix:"if (age >= 18) {",explanation:"> excludes the boundary, >= includes it. Always test the exact edge value when you write a comparison."},
{title:"The Wrong Price Tag",out:["30", "10 1"],extra:"console.log(total(5, 2), total(1, 1));",task:"Return the total cost of qty items at price each.",category:"wrong-variable",expected:"30",actual:"2",
 code:`const taxRate = 0.2;\n\nfunction total(price, qty) {\n§  return price * taxRate;\n}\n\nconsole.log(total(10, 3)); // 3 items at 10 each`,
 hints:["The total ignores something the task mentions. What is missing?","Look at which variables the return line uses.","Is qty used anywhere in the function?"],
 fix:"return price * qty;",explanation:"The right operator with the wrong variable still gives the wrong answer. Read each name and ask 'is this the one I mean?'"},
{title:"The Missing Five",out:["15"],task:"Add the numbers 1 to 5.",category:"off-by-one",expected:"15",actual:"10",
 code:`let sum = 0;\n\n§for (let i = 1; i < 5; i++) {\n  sum += i;\n}\n\nconsole.log(sum); // 1+2+3+4+5`,
 hints:["10 is 1+2+3+4. Which number never got added?","The last value is skipped. Check the loop's stopping rule.","Does < 5 include the value 5?"],
 fix:"for (let i = 1; i <= 5; i++) {",explanation:"< stops before the limit, <= includes it. When the last number matters, check whether the limit is inclusive."},
{title:"Even Steven",out:["even", "odd even even"],extra:"console.log(label(7), label(10), label(0));",task:"Return 'even' for even numbers and 'odd' otherwise.",category:"bad-condition",expected:"even",actual:"odd",
 code:`function label(n) {\n§  if (n % 2 === 1) {\n    return "even";\n  }\n  return "odd";\n}\n\nconsole.log(label(4));`,
 hints:["4 is clearly even, yet the answer is wrong. Which branch ran?","What does n % 2 give for an even number?","If n % 2 is 0 for even numbers, is the test checking for 1 right?"],
 fix:"if (n % 2 === 0) {",explanation:"A condition guards a branch, so it must describe exactly the case you mean. Trace one value through it by hand."},
{title:"Times Table Twist",out:["1 2 3 ", "2 4 6 ", "3 6 9 "],task:"Print a 3x3 multiplication table (rows are i, columns are j).",category:"wrong-variable",expected:"1 2 3 / 2 4 6 / 3 6 9",actual:"1 1 1 / 4 4 4 / 9 9 9",
 code:`for (let i = 1; i <= 3; i++) {\n  let row = "";\n  for (let j = 1; j <= 3; j++) {\n§    row += i * i + " ";\n  }\n  console.log(row);\n}`,
 hints:["Every row repeats the same number. Which variable never changes within a row?","Two loops, i and j. Which one changes across a row?","The inner loop's variable isn't used anywhere. Where should it appear?"],
 fix:'row += i * j + " ";',explanation:"With nested loops, each variable has a job. If a loop variable is never used, suspect a typo."},
{title:"Heart Drain",out:["Heart 0", "Heart 1", "Heart 2"],task:"Print Heart 0, Heart 1, Heart 2 and then stop.",category:"infinite-loop",expected:"Heart 0, 1, 2",actual:"Heart 0, -1, -2, -3... forever",
 code:`let lives = 0;\n\nwhile (lives < 3) {\n  console.log("Heart", lives);\n§  lives--;\n}`,
 hints:["The hearts count the wrong way. Which line changes lives?","The loop runs while lives < 3. Does the number get closer to 3?","Should lives go down or up for the condition to end?"],
 fix:"lives++;",explanation:"Always check that the update moves the variable toward the stopping condition."},
{title:"Pizza Party Problem",out:["Each friend gets 3 slices"],task:"Share 12 pizza slices equally between 4 friends.",category:"wrong-operator",expected:"Each friend gets 3 slices",actual:"Each friend gets 0 slices",
 code:`const slices = 12;\nconst friends = 4;\n\n§const perFriend = slices % friends;\n\nconsole.log("Each friend gets", perFriend, "slices");`,
 hints:["The answer is 0, but 12 slices shared by 4 friends can't be 0. Which line works out the answer?","Look at the symbol between slices and friends.","% gives what is LEFT OVER after dividing. Which symbol actually divides?"],
 fix:"const perFriend = slices / friends;",explanation:"% is the remainder, not the share. Use / to divide."},
{title:"Hot or Not",out:["Hot day!"],task:"Say 'Hot day!' when the temperature is above 30.",category:"bad-condition",expected:"Hot day!",actual:"Cool day.",
 code:`const temp = 35;\n\n§if (temp < 30) {\n  console.log("Hot day!");\n} else {\n  console.log("Cool day.");\n}`,
 hints:["35 is hot, yet it says 'Cool'. Which line decides between the two messages?","Read the test out loud: 'if temp is ___ 30'. Does it match the task?","The task says ABOVE 30. Which symbol means above?"],
 fix:"if (temp > 30) {",explanation:"An if-test must match the sentence in the task. Say it in words, then check the symbol."},
{title:"Hello, Nobody",out:["Hello, Sam"],task:"Greet Sam by name.",category:"wrong-variable",expected:"Hello, Sam",actual:"Error: nmae is not defined",
 code:`const name = "Sam";\nconst greeting = "Hello, ";\n\n§console.log(greeting + nmae);`,
 hints:["The program crashes with a message about a name it doesn't know.","Compare the spelling of the variable you made with the one you used.","One variable is spelled name. The other is spelled differently."],
 fix:"console.log(greeting + name);",explanation:"A typo in a variable name makes a brand-new name the computer has never seen. Match spellings exactly."},
{title:"The Last Letter",out:["Last letter: o"],task:"Print the last letter of the word.",category:"off-by-one",expected:"Last letter: o",actual:"Last letter: undefined",
 code:`const word = "hello";\n\n§const last = word[word.length];\n\nconsole.log("Last letter:", last);`,
 hints:["undefined means we asked for something that isn't there.","'hello' has 5 letters. Counting from 0, what is the last position?","Positions go 0,1,2,3,4. What is word.length?"],
 fix:"const last = word[word.length - 1];",explanation:"Positions start at 0, so the last one is length - 1."},
{title:"Double Trouble",out:["Four doubled: 8", "20 0"],extra:"console.log(double(10), double(0));",task:"Double a number and print it.",category:"missing-return",expected:"Four doubled: 8",actual:"Four doubled: undefined",
 code:`function double(n) {\n§  n * 2;\n}\n\nconsole.log("Four doubled:", double(4));`,
 hints:["It prints undefined. Is any value coming OUT of the function?","The line works out n * 2. Where does that answer go?","How does a function hand its answer back to the code that called it?"],
 fix:"return n * 2;",explanation:"Working something out isn't the same as returning it. Without return, a function gives back undefined."},
{title:"Damage Dealer",out:["Total damage: 21"],task:"Total damage is the number of hits times the power of each hit.",category:"wrong-operator",expected:"Total damage: 21",actual:"Total damage: 10",
 code:`const hits = 3;\nconst power = 7;\n\n§const damage = hits + power;\n\nconsole.log("Total damage:", damage);`,
 hints:["3 hits of 7 power each should be a lot more than 10.","Look at the symbol between hits and power.","Does + combine them the way 'times' does?"],
 fix:"const damage = hits * power;",explanation:"+ adds, * multiplies. Match the symbol to the word in the task: 'times' means *."},
{title:"Bigger Number",out:["8", "9 5"],extra:"console.log(bigger(9, 2), bigger(5, 5));",task:"Return whichever of two numbers is bigger.",category:"wrong-variable",expected:"8",actual:"3",
 code:`function bigger(a, b) {\n  if (a > b) {\n    return a;\n  }\n§  return a;\n}\n\nconsole.log(bigger(3, 8));`,
 hints:["bigger(3, 8) should be 8, but it gives 3. Which return runs?","3 is not bigger than 8, so the if is skipped. What does the last line return?","The last line returns a. Should it?"],
 fix:"return b;",explanation:"Two near-identical lines are easy to copy wrongly. When the 'else' path returns the wrong variable, check which name you really mean."},
{title:"Level Up!",out:["Level up!"],task:"Say 'Level up!' when xp is 100 or more.",category:"bad-condition",expected:"Level up!",actual:"Keep training.",
 code:`const xp = 120;\n\n§if (xp < 100) {\n  console.log("Level up!");\n} else {\n  console.log("Keep training.");\n}`,
 hints:["120 xp is plenty, yet it says 'Keep training.'","Read the if-test out loud in words. Does it say what the task says?","The test checks for LESS than 100. Is that when you level up?"],
 fix:"if (xp >= 100) {",explanation:"A condition must say exactly the case you mean. Read it aloud and compare it with the task."},
{title:"Birthday Candles",out:["candle 1", "candle 2", "candle 3"],task:"Print one line per candle for a 3 year old.",category:"off-by-one",expected:"3 candle lines",actual:"4 candle lines",
 code:`const age = 3;\n\n§for (let i = 0; i <= age; i++) {\n  console.log("candle", i + 1);\n}`,
 hints:["Count the lines it prints. How many should there be?","One candle too many. Which part of the loop decides when to stop?","Starting at 0, does <= 3 stop after 3 candles or 4?"],
 fix:"for (let i = 0; i < age; i++) {",explanation:"Starting from 0, < age runs exactly age times. <= age runs one extra time."},
{title:"Stuck Spinner",out:["spin", "spin", "spin"],task:"Print 'spin' three times, then stop.",category:"infinite-loop",expected:"spin, spin, spin",actual:"spin forever",
 code:`let spins = 3;\n\nwhile (spins > 0) {\n  console.log("spin");\n§  spins = spins + 1;\n}`,
 hints:["The spinner never stops. What does the while-test keep checking?","The loop runs while spins > 0. Does spins ever reach 0?","Each pass makes spins bigger. Which way must it move to hit 0?"],
 fix:"spins = spins - 1;",explanation:"A loop ends only if each pass moves its counter toward the stopping condition."},
{title:"Village Lantern",out:["8pm lantern on? true", "false true true"],extra:"console.log(lanternOn(9), lanternOn(18), lanternOn(23));",quest:true,task:"The lantern should switch on from 6pm (hour 18) onwards.",category:"bad-condition",expected:"8pm lantern on? true",actual:"8pm lantern on? false",
 code:`// The village lantern should switch on from 6pm (hour 18) onwards.\nfunction lanternOn(hour) {\n§  return hour < 18;\n}\n\nconsole.log("8pm lantern on?", lanternOn(20));`,
 hints:["At 8pm the lantern should be on, but the answer is false. Which line gives that answer?","Read the test aloud: 'hour is LESS than 18'. When is the lantern meant to be on?","It should be on from 18 upwards. Which comparison means 'from 18 up'?"],
 fix:"return hour >= 18;",explanation:"A condition must describe exactly the case you mean. Say it in words, then compare it with the task."},
{title:"Water Pump",out:["Tank after 3 strokes: 30", "10 12"],extra:"console.log(fill(2, 5), fill(4, 3));",quest:true,task:"Each stroke of the pump moves a number of litres. Work out the total.",category:"wrong-variable",expected:"Tank after 3 strokes: 30",actual:"Tank after 3 strokes: 9",
 code:`// Each stroke of the pump moves some litres of water.\nfunction fill(strokes, litres) {\n§  return strokes * strokes;\n}\n\nconsole.log("Tank after 3 strokes:", fill(3, 10));`,
 hints:["3 strokes of 10 litres should be 30, but it says 9. Which line works out the total?","Two names are multiplied. Are they the two names you actually need?","The line uses strokes twice. What happened to litres?"],
 fix:"return strokes * litres;",explanation:"The right operator with the wrong variable still gives the wrong answer. Check each name: is it the one I mean?"},
{title:"Village Bell",out:["3pm tolls: 3", "1 7 9"],extra:"console.log(tolls(13), tolls(7), tolls(21));",quest:true,task:"The bell tolls once for each hour on a 12-hour clock.",category:"missing-return",expected:"3pm tolls: 3",actual:"3pm tolls: undefined",
 code:`// The bell tolls once for each hour on a 12-hour clock.\nfunction tolls(hour) {\n§  hour % 12;\n}\n\nconsole.log("3pm tolls:", tolls(15));`,
 hints:["It prints undefined. Is any value coming OUT of the function?","The line works out hour % 12. Where does that answer go?","How does a function hand its answer back to whoever called it?"],
 fix:"return hour % 12;",explanation:"Working something out isn't the same as returning it. Without return, a function gives back undefined."},
{title:"Meadow Compiler",out:["Compiled bytes: 27", "0 5 10"],extra:"console.log(compile([]), compile([5]), compile([1, 2, 3, 4]));",quest:true,task:"The Meadow Compiler adds up the size of every file it builds.",category:"wrong-operator",expected:"Compiled bytes: 27",actual:"Compiled bytes: 15",
 code:`// The Meadow Compiler adds up the size of every file it builds.\nfunction compile(files) {\n  let total = 0;\n  for (let i = 0; i < files.length; i++) {\n§    total = files[i];\n  }\n  return total;\n}\n\nconsole.log("Compiled bytes:", compile([4, 8, 15]));`,
 hints:["27 bytes in total, but only 15 comes out, which is just the last file. Which line handles each file?","On every pass, what happens to the old total?","Each pass replaces total. Which operator keeps the old value AND adds the new one?"],
 fix:"total += files[i];",explanation:"= replaces, += accumulates. In a running total, ask whether the old value survives each pass."},
{title:"Rope Bridge",forestWild:true,out:["Planks needed: 11", "7 5"],extra:"console.log(planks(\"2\", \"5\"), planks(4, 1));",r2:true,task:"Add the planks on both sides of the bridge to get the number it needs.",category:"type-mix-up",expected:"Planks needed: 11",actual:"Planks needed: 83",
 code:`// The bridge needs the planks from the left bank plus the right bank.\nfunction planks(left, right) {\n§  return left + right;\n}\n\nconsole.log("Planks needed:", planks("8", 3));`,
 hints:["It should be 11, but it prints 83. What kind of thing is the text '8'?","'8' is text, 3 is a number. What does + do when one side is text?","Which function turns text like '8' into a real number you can add?"],
 fix:"return Number(left) + Number(right);",explanation:"+ glues text together when either side is text. Convert text to numbers first (Number(...)) when you want to do arithmetic."},
{title:"Lockbox",forestWild:true,out:["Wrong tries: 2"],r2:true,task:"The lockbox counts how many wrong tries you made.",category:"scope",expected:"Wrong tries: 2",actual:"it crashes: Cannot access 'tries' before initialization",
 code:`// The lockbox counts how many wrong tries you made.\nlet tries = 0;\nfunction wrongTry() {\n§  let tries = tries + 1;\n}\nwrongTry();\nwrongTry();\nconsole.log("Wrong tries:", tries);`,
 hints:["The program crashes on the line inside the function. What does let do?","Inside the function, let creates a brand-new tries that hides the outer one. Is that what you want?","How do you update an existing variable without declaring a new one?"],
 fix:"tries = tries + 1;",explanation:"let makes a NEW variable that hides the outer one (this is called shadowing). To change the outer variable, leave out let."},
{title:"Vine Gate",forestWild:true,out:["Gate opens for 42: true", "false true false"],extra:"console.log(opens(41), opens(42), opens(7));",r2:true,task:"The vine gate opens only for the secret number 42.",category:"type-mix-up",expected:"Gate opens for 42: true",actual:"Gate opens for 42: false",
 code:`// The vine gate opens only for the secret number 42.\nfunction opens(code) {\n§  return code === "42";\n}\n\nconsole.log("Gate opens for 42:", opens(42));`,
 hints:["42 is the right number, yet the gate stays shut. What are you comparing?","=== compares value AND type. What type is '42' in quotes?","The secret is a number. Should it be written in quotes?"],
 fix:"return code === 42;",explanation:"=== is strict: the number 42 and the text '42' are different types, so they're not equal. Compare like with like."},
{title:"Syntax Shrine",forestWild:true,out:["Shrine glow: 15", "0 4 4"],extra:"console.log(totalGlow([]), totalGlow([4]), totalGlow([1, 1, 1, 1]));",r2:true,task:"The shrine adds up the glow of every lantern it finds.",category:"scope",expected:"Shrine glow: 15",actual:"it crashes: Cannot access 'glow' before initialization",
 code:`// The shrine adds up the glow of every lantern it finds.\nfunction totalGlow(lanterns) {\n  let glow = 0;\n  for (let i = 0; i < lanterns.length; i++) {\n§    let glow = glow + lanterns[i];\n  }\n  return glow;\n}\n\nconsole.log("Shrine glow:", totalGlow([2, 5, 8]));`,
 hints:["It crashes on the line inside the loop. What does let do there?","The loop body declares a new glow every pass. Which glow is the function returning?","How do you add to the existing glow without making a new variable?"],
 fix:"glow = glow + lanterns[i];",explanation:"A let inside the loop makes a fresh, empty variable each time and hides the outer one. To keep a running total, update the outer variable."},
{title:"Mushroom Market",out:["Mushrooms: 9"],r2:true,task:"Add the two basket sizes to get the total number of mushrooms.",category:"type-mix-up",expected:"Mushrooms: 9",actual:"Mushrooms: 72",
 code:`const small = "7";\nconst big = "2";\n\n§const total = small + big;\n\nconsole.log("Mushrooms:", total);`,
 hints:["Seven plus two should be nine. What shows up instead?","Both values are written in quotes. What does that make them?","Which function turns text into a number?"],
 fix:"const total = Number(small) + Number(big);",explanation:"Numbers written in quotes are text, and + glues text together. Convert with Number(...) before adding."},
{title:"Ranger Age Check",out:["Adult ticket"],r2:true,task:"Show 'Adult ticket' for age 18.",category:"type-mix-up",expected:"Adult ticket",actual:"Child ticket",
 code:`const age = 18;\n\n§if (age === "18") {\n  console.log("Adult ticket");\n} else {\n  console.log("Child ticket");\n}`,
 hints:["Age is 18, yet it says Child ticket. Which branch ran?","What are you comparing 18 against?","Is '18' in quotes the same as the number 18?"],
 fix:"if (age === 18) {",explanation:"=== checks the type too: the number 18 is not equal to the text '18'."},
{title:"Size Contest",out:["10 is bigger"],r2:true,task:"Say which of two number-like values is bigger.",category:"type-mix-up",expected:"10 is bigger",actual:"9 is bigger",
 code:`const a = "10";\nconst b = "9";\n\n§if (a > b) {\n  console.log("10 is bigger");\n} else {\n  console.log("9 is bigger");\n}`,
 hints:["10 is obviously bigger than 9. Why does the program disagree?","Both values are text. How does the computer compare two pieces of text?","Text is compared letter by letter, so '9' comes after '1'. How do you compare as numbers?"],
 fix:"if (Number(a) > Number(b)) {",explanation:"Text is compared alphabetically ('9' > '10'). Convert to numbers first when you mean numeric size."},
{title:"Lost Bonus",out:["Total: 15"],r2:true,task:"Add a bonus to the score and print the total.",category:"scope",expected:"Total: 15",actual:"it crashes: bonus is not defined",
 code:`let score = 10;\n\nif (score > 5) {\n§  let bonus = 5;\n}\n\nconsole.log("Total:", score + bonus);`,
 hints:["The program crashes saying bonus is not defined. Where is bonus created?","A variable made with let lives only inside its { } block. Where do you use it?","Which keyword makes a variable available outside the block?"],
 fix:"var bonus = 5;",explanation:"let variables exist only inside the { } they're declared in. var is wider, or you can declare the variable before the block."},
{title:"Shadow Counter",out:["Count: 4"],r2:true,task:"Count up to 4 using a counter.",category:"scope",expected:"Count: 4",actual:"it crashes: Cannot access 'count' before initialization",
 code:`let count = 0;\n\nfor (let i = 0; i < 4; i++) {\n§  let count = count + 1;\n}\n\nconsole.log("Count:", count);`,
 hints:["It crashes inside the loop. What does let do each time round?","A new count is declared every pass, and it hides the outer one.","How do you change the outer count without creating a new one?"],
 fix:"count = count + 1;",explanation:"let inside the loop shadows the outer variable. Drop the let to update the one you want."},
{title:"Lantern Switch",out:["At 18:00 lanterns on? true", "false true true false false"],extra:"console.log(lanternsOn(17), lanternsOn(23), lanternsOn(5), lanternsOn(6), lanternsOn(12));",quest2:true,r2:true,task:"The lanterns switch on at 18:00 or later, and stay on until 06:00.",category:"bad-condition",expected:"At 18:00 lanterns on? true",actual:"At 18:00 lanterns on? false",
 code:`// The lanterns switch on at 18:00 or later, and stay on until 06:00.\nfunction lanternsOn(hour) {\n§  return hour > 18 || hour < 6;\n}\n\nconsole.log("At 18:00 lanterns on?", lanternsOn(18));`,
 hints:["The lanterns should be on at exactly 18:00, but they're off. Which line decides?","Read the test aloud: 'hour is MORE than 18'. What about exactly 18?","Which comparison means '18 or more'?"],
 fix:"return hour >= 18 || hour < 6;",explanation:"Boundary values are where conditions break. 'More than 18' leaves out 18 itself: use >= when the edge should be included."},
{title:"Relay Pulse",out:["Pulses from 3: 3", "0 4"],extra:"console.log(pulses(0), pulses(4));",quest2:true,r2:true,task:"The relay sends one pulse for every number from the start down to 1.",category:"infinite-loop",expected:"Pulses from 3: 3",actual:"it never finishes (the loop runs forever)",
 code:`// The relay sends one pulse for every number from the start down to 1.\nfunction pulses(start) {\n  let count = 0;\n§  for (let n = start; n > 0; n++) {\n    count = count + 1;\n  }\n  return count;\n}\n\nconsole.log("Pulses from 3:", pulses(3));`,
 hints:["The relay never stops pulsing. Which line decides when the loop ends?","The loop runs while n > 0. Does n ever stop being bigger than 0?","Counting DOWN from the start toward 1: should n go up or down each time?"],
 fix:"for (let n = start; n > 0; n--) {",explanation:"A loop only ends if each pass moves its counter toward the stopping condition. Counting down means n--."},
{title:"Bridge Planks",out:["Planks for length 5: 5", "0 1 8"],extra:"console.log(planks(0), planks(1), planks(8));",quest2:true,r2:true,task:"The bridge needs one plank for every step from 1 up to its length, including the last.",category:"off-by-one",expected:"Planks for length 5: 5",actual:"Planks for length 5: 4",
 code:`// The bridge needs one plank for every step from 1 up to its length (inclusive).\nfunction planks(length) {\n  let list = [];\n§  for (let i = 1; i < length; i++) {\n    list.push("plank " + i);\n  }\n  return list.length;\n}\n\nconsole.log("Planks for length 5:", planks(5));`,
 hints:["A bridge of length 5 should have 5 planks, but there are 4. Which one is missing?","Which line decides how many times the loop runs?","Counting from 1, does i < length include the last step?"],
 fix:"for (let i = 1; i <= length; i++) {",explanation:"Counting from 1 up to length INCLUDING length needs <=. With < the last step is skipped."},
{title:"Nullo's Count",out:["Even numbers up to 10: 5", "0 1 3"],extra:"console.log(countEven(1), countEven(2), countEven(7));",quest2:true,r2:true,task:"Count the even numbers from 1 up to limit, including limit itself.",category:"off-by-one",expected:"Even numbers up to 10: 5",actual:"Even numbers up to 10: 4",
 code:`// Count the even numbers from 1 up to limit (including limit itself).\nfunction countEven(limit) {\n  let count = 0;\n§  for (let i = 1; i < limit; i++) {\n    if (i % 2 === 0) {\n      count = count + 1;\n    }\n  }\n  return count;\n}\n\nconsole.log("Even numbers up to 10:", countEven(10));`,
 hints:["There are five even numbers up to 10 (2, 4, 6, 8, 10), but it counts four. Which is missing?","10 is itself even. Is it being checked?","Which loop line stops before reaching limit?"],
 fix:"for (let i = 1; i <= limit; i++) {",explanation:"The loop stops before it reaches limit, so limit itself is never checked. Use <= when the last value counts."},
{title:"Forest Compiler",out:["Slowest build: 9", "0 7 5 10"],extra:"console.log(slowest([]), slowest([7]), slowest([3, 3, 5, 1]), slowest([10, 2]));",quest2:true,r2:true,task:"The Forest Compiler reports its slowest build time, or 0 when there are no builds.",category:"bad-condition",expected:"Slowest build: 9",actual:"Slowest build: 0",
 code:`// The Forest Compiler reports its slowest build time, or 0 when there are no builds.\nfunction slowest(times) {\n  let best = 0;\n  for (let i = 0; i < times.length; i++) {\n§    if (times[i] < best) {\n      best = times[i];\n    }\n  }\n  return best;\n}\n\nconsole.log("Slowest build:", slowest([4, 9, 2]));`,
 hints:["The slowest of 4, 9 and 2 should be 9, but it says 0. Which line chooses the new best?","best starts at 0. Is any build time smaller than 0?","To find the BIGGEST value, should you replace best with something smaller or bigger?"],
 fix:"if (times[i] > best) {",explanation:"To find a maximum you replace best whenever you see something bigger. The test pointed the wrong way, so nothing ever replaced the starting 0."}
];
const BANK=RAW.map(r=>{const ls=r.code.split("\n");let bl=-1;
 const code=ls.map((l,i)=>{if(l[0]==="§"){bl=i+1;return l.slice(1)}return l}).join("\n");
 return {...r,code,bug_line:bl}});
const OKS={"Coin Collector Glitch":["wrong-operator"],"Countdown Lift-Off":["infinite-loop","wrong-operator"],"The Lonely Last Song":["off-by-one","bad-condition"],
 "The Silent Function":["missing-return"],"Is It Legal to Drive?":["bad-condition","wrong-operator","off-by-one"],"The Wrong Price Tag":["wrong-variable"],
 "The Missing Five":["off-by-one","bad-condition","wrong-operator"],"Even Steven":["bad-condition","wrong-operator"],"Times Table Twist":["wrong-variable"],
 "Heart Drain":["infinite-loop","wrong-operator"],"Pizza Party Problem":["wrong-operator"],"Hot or Not":["bad-condition","wrong-operator"],
 "Hello, Nobody":["wrong-variable"],"The Last Letter":["off-by-one"],"Double Trouble":["missing-return"],"Damage Dealer":["wrong-operator"],
 "Bigger Number":["wrong-variable"],"Level Up!":["bad-condition","wrong-operator"],"Birthday Candles":["off-by-one","bad-condition","wrong-operator"],
 "Stuck Spinner":["infinite-loop","wrong-operator"],"Village Lantern":["bad-condition","wrong-operator"],"Water Pump":["wrong-variable"],"Village Bell":["missing-return"],"Meadow Compiler":["wrong-operator"],"Rope Bridge":["type-mix-up","wrong-operator"],"Lockbox":["scope","wrong-variable"],"Vine Gate":["type-mix-up","bad-condition"],"Syntax Shrine":["scope","wrong-variable"],"Mushroom Market":["type-mix-up","wrong-operator"],"Ranger Age Check":["type-mix-up","bad-condition"],"Size Contest":["type-mix-up","bad-condition","wrong-operator"],"Lost Bonus":["scope"],"Shadow Counter":["scope","wrong-variable"]};
BANK.forEach(b=>{b.ok=(OKS[b.title]||[b.category]).slice();if(!b.ok.includes(b.category))b.ok.push(b.category)});
// ---- mistake categories. The first six appear in Region 1; Region 2 adds the last two. ----
const CATS=["off-by-one","wrong-operator","wrong-variable","bad-condition","missing-return","infinite-loop"];
const CATS8=["off-by-one","wrong-operator","wrong-variable","bad-condition","missing-return","infinite-loop","type-mix-up","scope"];
// labels that can honestly describe the same mistake: never offer one as a "wrong" decoy
const FAM=[["bad-condition","wrong-operator","off-by-one"],["infinite-loop","wrong-operator","off-by-one"],["scope","wrong-variable"],["type-mix-up","bad-condition","wrong-operator"]];
const blurry=c=>{const r=new Set([c]);FAM.forEach(g=>{if(g.includes(c))g.forEach(x=>r.add(x))});return r};
